CREATE USER ie WITH
	LOGIN
	SUPERUSER
	CREATEDB
	CREATEROLE
	INHERIT
	REPLICATION
	CONNECTION LIMIT -1
	PASSWORD 'xxxxxx';

CREATE DATABASE ie
    WITH
    OWNER = ie
    ENCODING = 'UTF8'
    CONNECTION LIMIT = -1;