export default {
    'login.top.title' : 'سامانه انتقادات و پیشنهادات',
    'login.top.text' : 'ورود به سامانه',
    'common.username' : 'نام کاربری',
    'common.password' : 'رمز عبور',
    'common.login' : 'ورود',
    'login.sublogo.text' : 'سامانه انتقادات و پیشنهادات',
    'common.error.header' : 'خطا در عملیات',
    'authentication.failed' : 'نام کاربری یا رمز عبور نادرست است.',
    'common.submit.error' : 'خطا در ثبت',
    'common.success.header' : 'عملیات با موفقیت انجام شد',
    'common.validation.failed' : 'اطلاعات ورودی نادرست است.',
    'menu.dashboard' : 'داشبرد',
    'menu.profile': 'پروفایل',
    'menu.create.ticket' : 'ثبت تیکت',
    'menu.manage.user.ticket' : 'مشاهده تیکت ها',
    'menu.user.list' : 'فهرست کاربران',
    'menu.unconfirmed.user.lists' : 'کاربران تایید نشده',
    'menu.tickets.management' : 'مدیریت تیکت ها',
    'common.fullname' : 'نام و نام خانوادگی',
    'common.email' : 'ایمیل',
    'user.type' : 'نوع کاربر',
    'profile.update.success' : 'مشخصات کاربری شما با موفقیت بروزرسانی شد',
    'password.update.success' : 'بروزرسانی رمزعبور با موفقیت انجام شد.',
    'current.password': 'رمز عبور فعلی',
    'new.password': 'رمز عبور جدید',
    'common.submit': 'ثبت',
    'reset.password': 'تغییر رمز عبور',
    'ticket.submit.success' : 'تیکت با موفقیت ثبت شد.',
    'common.title' : 'عنوان',
    'ticket.body': "متن",
    'assignee.user': "ارجاع به",
    'user.tickets.created' : 'تیکت های صادر شده من',
    'user.tickets.assigned' : 'ارجاع داده شده به من',
    'common.row': 'ردیف',
    'ticket.creator': 'صادر کننده',
    'ticket.assignee': 'گیرنده',
    'common.status': 'وضعیت',
    'common.empty.table.text': 'موردی یافت نشد.',
    'common.actions': 'عملیات',
    'user.activate.success': 'تایید کاربر با موفقیت انجام شد.',
    'user.activated': 'تایید شده',
    'user.activate': 'تایید',
    'user.enable': 'فعال سازی',
    'user.disable': 'غیر فعال سازی',
    'user.enable.success': 'فعال سازی کاربر با موفقیت انجام شد.',
    'user.disable.success': 'غیر فعال سازی کاربر با موفقیت انجام شد.',
    'sign.up.title': 'ثبت نام',
    'common.register': 'ثبت نام',
    'user.create.success': 'حساب کاربری شما با موفقیت ساخته شد. در صورت نیاز پس از تایید مدیر حساب شما فعال می شود.',
    'user.inactive': 'حساب کاربری شما فعال نشده است.',
    'duplicate.user': 'حساب کاربری در سامانه موجود است.',
    'invalid.input.data': 'خطا در داده های ورودی',
    'invalid.old.password': 'رمز عبور وارد شده نادرست است.',
    'user.not.found': 'کاربر یافت نشد.',
    'ticket.not.found': 'تیکت یافت نشد.',
    'unknown.exception': 'خطای ناشناخته',
    'bad.credentials': 'نام کاربری یا رمز عبور نادرست است.',
    'ticket.details': 'جزِئیات',
    'comment.add.success': 'نظر با موفقیت ثبت شد.',
    'common.required' : 'اجباری',
}