export default {
    'login.top.title' : 'سامانه انتقادات و پیشنهادات',
    'login.top.text' : 'ورود به سامانه',
    'common.username' : 'نام کاربری',
    'common.password' : 'رمز عبور',
    'common.login' : 'ورود',
    'login.sublogo.text' : 'سامانه انتقادات و پیشنهادات',
    'common.error.header' : 'خطا در عملیات',
    'authentication.failed' : 'نام کاربری یا رمز عبور نادرست است.',
    'common.submit.error' : 'خطا در ثبت',
    'common.success.header' : 'عملیات با موفقیت انجام شد',
    'common.validation.failed' : 'اطلاعات ورودی نادرست است.',
    'menu.dashboard' : 'داشبرد',
    'menu.profile': 'پروفایل',
    'menu.create.ticket' : 'ثبت تیکت',
    'menu.manage.user.ticket' : 'مشاهده تیکت ها',
    'menu.user.list' : 'فهرست کاربران',
    'menu.unconfirmed.user.lists' : 'کاربران تایید نشده',
    'menu.tickets.management' : 'مدیریت تیکت ها',
    'common.fullname' : 'نام و نام خانوادگی',
    'common.email' : 'ایمیل',
    'user.type' : 'نوع کاربر',
    'profile.update.success' : 'مشخصات کاربری شما با موفقیت بروزرسانی شد',
    'password.update.success' : 'بروزرسانی رمزعبور با موفقیت انجام شد.',
    'current.password': 'رمز عبور فعلی',
    'new.password': 'رمز عبور جدید',
    'common.submit': 'ثبت',
    'reset.password': 'تغییر رمز عبور',
    'ticket.submit.success' : 'تیکت با موفقیت ثبت شد.',
    'common.title' : 'عنوان',
    'ticket.body': "متن",
    'assignee.user': "ارجاع به",
    'user.tickets.created' : 'تیکت های صادر شده من',
    'user.tickets.assigned' : 'ارجاع داده شده به من',
    'common.row': 'ردیف',
    'ticket.creator': 'صادر کننده',
    'ticket.assignee': 'گیرنده',
    'common.status': 'وضعیت',
    'common.empty.table.text': 'موردی یافت نشد.',
    'common.actions': 'عملیات',
}